apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: whatsapp
  labels:
    app: whatsapp
spec:
  selector:
    matchLabels:
      app: whatsapp
  replicas: 1
  template:
    metadata:
      labels:
        app: whatsapp
    spec:
      containers:
      - name: whatsapp
        image: jailonso/datadog-app-whatsapp:v0 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
